#pragma once
#include <stdbool.h>

// For setting the CAN device
typedef enum {
  SYSTEM_CAN_DEVICE_BABYDRIVER = 0,
  SYSTEM_CAN_DEVICE_BMS_CARRIER = 1,
  SYSTEM_CAN_DEVICE_CENTRE_CONSOLE = 2,
  SYSTEM_CAN_DEVICE_CHARGER = 3,
  SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER = 4,
  SYSTEM_CAN_DEVICE_PEDAL = 5,
  SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_FRONT = 6,
  SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_REAR = 7,
  SYSTEM_CAN_DEVICE_POWER_SELECT = 8,
  SYSTEM_CAN_DEVICE_SOLAR_5_MPPTS = 9,
  SYSTEM_CAN_DEVICE_SOLAR_6_MPPTS = 10,
  SYSTEM_CAN_DEVICE_STEERING = 11,
  SYSTEM_CAN_DEVICE_NEW_CAN = 12,
  SYSTEM_CAN_DEVICE_CAN_ONE_SHOT_MODE = 13,
  NUM_SYSTEM_CAN_DEVICES = 14
} SystemCanDevice;

#define SYSTEM_CAN_MESSAGE_BABYDRIVER_BABYDRIVER (63 << 5) + SYSTEM_CAN_DEVICE_BABYDRIVER

#define SYSTEM_CAN_MESSAGE_BMS_CARRIER_BPS_HEARTBEAT (0 << 5) + SYSTEM_CAN_DEVICE_BMS_CARRIER

#define SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_VT (30 << 5) + SYSTEM_CAN_DEVICE_BMS_CARRIER

#define SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_AGGREGATE_VC \
  (33 << 5) + SYSTEM_CAN_DEVICE_BMS_CARRIER

#define SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_FAN_STATE (57 << 5) + SYSTEM_CAN_DEVICE_BMS_CARRIER

#define SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_RELAY_STATE (58 << 5) + SYSTEM_CAN_DEVICE_BMS_CARRIER

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_SET_RELAY_STATES \
  (1 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_POWER_ON_MAIN_SEQUENCE \
  (6 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_POWER_OFF_MAIN_SEQUENCE \
  (7 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_POWER_ON_AUX_SEQUENCE \
  (8 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_DRIVE_OUTPUT (9 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_SET_EBRAKE_STATE \
  (10 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_REGEN_BRAKING (11 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_READY_TO_DRIVE \
  (13 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_BEGIN_PRECHARGE \
  (28 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_HAZARD (32 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_DISCHARGE_PRECHARGE \
  (31 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_STATE_TRANSITION_FAULT \
  (34 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_ALLOW_CHARGING \
  (49 << 5) + SYSTEM_CAN_DEVICE_CENTRE_CONSOLE

#define SYSTEM_CAN_MESSAGE_CHARGER_REQUEST_TO_CHARGE (48 << 5) + SYSTEM_CAN_DEVICE_CHARGER

#define SYSTEM_CAN_MESSAGE_CHARGER_CHARGER_CONNECTED_STATE (50 << 5) + SYSTEM_CAN_DEVICE_CHARGER

#define SYSTEM_CAN_MESSAGE_CHARGER_CHARGER_FAULT (53 << 5) + SYSTEM_CAN_DEVICE_CHARGER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_DRIVE_STATE \
  (22 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_PRECHARGE_COMPLETED \
  (29 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_CONTROLLER_VC \
  (35 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_VELOCITY \
  (36 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_STATUS \
  (37 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_SINK_TEMPS \
  (38 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_DSP_BOARD_TEMPS \
  (39 << 5) + SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER

#define SYSTEM_CAN_MESSAGE_PEDAL_PEDAL_OUTPUT (18 << 5) + SYSTEM_CAN_DEVICE_PEDAL

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_FRONT_UV_CUTOFF_NOTIFICATION \
  (45 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_FRONT

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_FRONT_FRONT_CURRENT_MEASUREMENT \
  (54 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_FRONT

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_FRONT_FRONT_PD_FAULT \
  (62 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_FRONT

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_REAR_LIGHTS_SYNC \
  (23 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_REAR

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_REAR_REAR_CURRENT_MEASUREMENT \
  (55 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_REAR

#define SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_REAR_REAR_PD_FAULT \
  (61 << 5) + SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION_REAR

#define SYSTEM_CAN_MESSAGE_POWER_SELECT_POWER_SELECT_STATUS \
  (1 << 5) + SYSTEM_CAN_DEVICE_POWER_SELECT

#define SYSTEM_CAN_MESSAGE_POWER_SELECT_POWER_SELECT_AUX_MEASUREMENTS \
  (2 << 5) + SYSTEM_CAN_DEVICE_POWER_SELECT

#define SYSTEM_CAN_MESSAGE_POWER_SELECT_POWER_SELECT_DCDC_MEASUREMENTS \
  (3 << 5) + SYSTEM_CAN_DEVICE_POWER_SELECT

#define SYSTEM_CAN_MESSAGE_SOLAR_5_MPPTS_RELAY_OPEN_OK_5_MPPTS \
  (14 << 5) + SYSTEM_CAN_DEVICE_SOLAR_5_MPPTS

#define SYSTEM_CAN_MESSAGE_SOLAR_5_MPPTS_SOLAR_DATA_5_MPPTS \
  (59 << 5) + SYSTEM_CAN_DEVICE_SOLAR_5_MPPTS

#define SYSTEM_CAN_MESSAGE_SOLAR_5_MPPTS_SOLAR_FAULT_5_MPPTS \
  (60 << 5) + SYSTEM_CAN_DEVICE_SOLAR_5_MPPTS

#define SYSTEM_CAN_MESSAGE_SOLAR_6_MPPTS_RELAY_OPEN_OK_6_MPPTS \
  (15 << 5) + SYSTEM_CAN_DEVICE_SOLAR_6_MPPTS

#define SYSTEM_CAN_MESSAGE_SOLAR_6_MPPTS_SOLAR_DATA_6_MPPTS \
  (51 << 5) + SYSTEM_CAN_DEVICE_SOLAR_6_MPPTS

#define SYSTEM_CAN_MESSAGE_SOLAR_6_MPPTS_SOLAR_FAULT_6_MPPTS \
  (52 << 5) + SYSTEM_CAN_DEVICE_SOLAR_6_MPPTS

#define SYSTEM_CAN_MESSAGE_STEERING_LIGHTS (24 << 5) + SYSTEM_CAN_DEVICE_STEERING

#define SYSTEM_CAN_MESSAGE_STEERING_HORN (25 << 5) + SYSTEM_CAN_DEVICE_STEERING

#define SYSTEM_CAN_MESSAGE_STEERING_CRUISE_CONTROL_COMMAND (41 << 5) + SYSTEM_CAN_DEVICE_STEERING

#define SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG1 (0 << 5) + SYSTEM_CAN_DEVICE_NEW_CAN

#define SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG2 (1 << 5) + SYSTEM_CAN_DEVICE_NEW_CAN

#define SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG3 (2 << 5) + SYSTEM_CAN_DEVICE_NEW_CAN

#define SYSTEM_CAN_MESSAGE_CAN_ONE_SHOT_MODE_ONE_SHOT_MSG \
  (0 << 5) + SYSTEM_CAN_DEVICE_CAN_ONE_SHOT_MODE
