#pragma once

enum GlobalErrorCode {
  NO_ERROR = 0,
  PEDAL_OFFLINE,
  MCI_CAN_FAULT,
  PD_OUTPUT_OVER_CURRENT,
  PD_AUX_FAULT,
  PD_DCDC_FAULT,
  PD_AUX_LOW,
  PD_AUXDCDC_OVERCURRENT,
  PD_AUXDCDC_OVERTEMP,
  PD_AUX_INVALID_STARTUP,
  PD_DCDC_FAULT_SIGNAL,
  SOLAR_NO_CURRENT,
  SOLAR_DEAD,
  BMSAFE_CELL_VOLT_FAULT,
  BMSCURRENT_PACK_CURRENT_FAULT,
  BMS_CELL_OVERTEMP,  // AFE AND CURRENT SENSE
  BMSCARRIER_PRECHARGE_TIMEOUT,
  PD_BMS_LOSS,
  BMSCARRIER_AFE_LOSS,
  BMSCARRIER_CURRENT_LOSS
} GlobalErrorCode;