from enum import Enum

class SystemCanDevice(int, Enum):
  SYSTEM_CAN_DEVICE_TELEMETRY = 0
  SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER = 1
  SYSTEM_CAN_DEVICE_BOOTLOADER = 2
  SYSTEM_CAN_DEVICE_CAN_COMMUNICATION = 3
  SYSTEM_CAN_DEVICE_CAN_DEBUG = 4
  SYSTEM_CAN_DEVICE_NEW_CAN = 5
  SYSTEM_CAN_DEVICE_BMS_CARRIER = 6
  SYSTEM_CAN_DEVICE_CENTRE_CONSOLE = 7
  SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION = 8
  NUM_SYSTEM_CAN_DEVICES = 9
  
class SystemCanMessageId(int, Enum):
    SYSTEM_CAN_MESSAGE_TELEMETRY_TELEMETRY_ID =  ((52 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_TELEMETRY) 
    SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_CONTROLLER_VC_ID =  ((35 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER) 
    SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_VELOCITY_ID = (36) 
    SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MOTOR_SINK_TEMPS_ID =  ((38 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER) 
    SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_DSP_BOARD_TEMPS_ID =  ((39 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_MOTOR_CONTROLLER) 
    SYSTEM_CAN_MESSAGE_MOTOR_CONTROLLER_MC_STATUS_ID = (4) 
    SYSTEM_CAN_MESSAGE_BOOTLOADER_BOOTLOADER_START_ID = (30) 
    SYSTEM_CAN_MESSAGE_BOOTLOADER_BOOTLOADER_DATA_ID = (31) 
    SYSTEM_CAN_MESSAGE_CAN_COMMUNICATION_ONE_SHOT_MSG_ID = (34) 
    SYSTEM_CAN_MESSAGE_CAN_DEBUG_TEST_DEBUG_ID = (35) 
    SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG1_ID =  ((31 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_NEW_CAN) 
    SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG2_ID =  ((32 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_NEW_CAN) 
    SYSTEM_CAN_MESSAGE_NEW_CAN_TRANSMIT_MSG3_ID =  ((33 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_NEW_CAN) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_STATUS_ID = (1) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_INFO_ID = (14) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_VT_ID = (15) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_BATTERY_RELAY_INFO_ID =  ((16 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_BMS_CARRIER) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_AFE1_STATUS_ID =  ((60 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_BMS_CARRIER) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_AFE2_STATUS_ID =  ((61 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_BMS_CARRIER) 
    SYSTEM_CAN_MESSAGE_BMS_CARRIER_AFE3_STATUS_ID =  ((62 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_BMS_CARRIER) 
    SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_CC_INFO_ID = (5) 
    SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_CC_PEDAL_ID = (3) 
    SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_CC_STEERING_ID = (6) 
    SYSTEM_CAN_MESSAGE_CENTRE_CONSOLE_CC_REGEN_ID = (8) 
    SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_CURRENT_MEASUREMENT_1_ID =  ((54 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION) 
    SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_CURRENT_MEASUREMENT_2_ID =  ((55 << 5) + SystemCanDevice.SYSTEM_CAN_DEVICE_POWER_DISTRIBUTION) 
    SYSTEM_CAN_MESSAGE_POWER_DISTRIBUTION_PD_STATUS_ID = (2) 