/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "adc.h"
#include "gpio.h"
#include "interrupt.h"
#include "log.h"
#include "soft_timer.h"
#include "task_test_helpers.h"
#include "test_helpers.h"
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setup_test(void);
extern void teardown_test(void);
extern void test_adc_pin_to_channel_conversion();
extern void test_adc_read_temp();
extern void test_pin_set_channel(void);
extern void test_pin_set_notification(void);
extern void test_pin_read_single(void);
extern void test_pin_read_continuous(void);
extern void test_adc_mock_reading(void);
extern void test_pin_single(void);
extern void test_pin_continuous(void);

/*=======Mock Management=====*/
static void CMock_Init(void) {}
static void CMock_Verify(void) {}
static void CMock_Destroy(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void) {
  teardown_test();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setup_test();
}
void verifyTest(void);
void verifyTest(void) {
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char *name, UNITY_LINE_TYPE line_num) {
  Unity.CurrentTestName = name;
  Unity.CurrentTestLineNumber = line_num;

  Unity.NumberOfTests++;
  UNITY_CLR_DETAILS();

  vTaskSuspendAll();
  setup_test();
  xTaskResumeAll();

  func();

  UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/
/*=======MAIN=====*/
TASK(test_task, TASK_STACK_4096) {
  UnityBegin("libraries/ms-common/test/test_adc.c");
  run_test(test_adc_pin_to_channel_conversion, "test_adc_pin_to_channel_conversion", 83);
  run_test(test_adc_read_temp, "test_adc_read_temp", 111);
  run_test(test_pin_set_channel, "test_pin_set_channel", 123);
  run_test(test_pin_set_notification, "test_pin_set_notification", 135);
  run_test(test_pin_read_single, "test_pin_read_single", 146);
  run_test(test_pin_read_continuous, "test_pin_read_continuous", 157);
  run_test(test_adc_mock_reading, "test_adc_mock_reading", 169);
  run_test(test_pin_single, "test_pin_single", 183);
  run_test(test_pin_continuous, "test_pin_continuous", 212);

  exit(UnityEnd());
}

int main(void) {
  setup_test();
  tasks_init_task(test_task, configMAX_PRIORITIES - 1, NULL);
  tasks_start();
  return 0;
}
