#pragma once

#define AUX_STATUS_BITS 0x02
#define AUX_FAULT_BITS 0xE0
#define PD_FRONT_FAULT 0x00
#define PD_REAR_FAULT 0x00
#define SET_BMS_POWER_NOTIFY 0x01  // Todo (Bafran): Change value to real value
#define BPS_HEARTBEAT 0x00
#define SET_CLOSE_RELAY_STATE_MASK 0x01
#define SET_CLOSE_RELAY_STATE_STATE 0x01
#define CLOSE_HV_STATUS 0x01
#define CLOSE_GND_STATUS 0x01
#define DCDC_STATUS_BITS 0x02
#define DCDC_FAULT_BITS 0x1C
#define POWER_SELECT_STATUS_STATUS 0x02
#define POWER_SELECT_STATUS_FAULT 0x1C
#define SET_TURN_ON_EVERYTHING_NOTIFICATION 0x00
#define SET_READY_TO_DRIVE 0x01
#define SET_DISCHARGE_PRECHARGE 0x01
#define SET_OPEN_RELAY_STATE_MASK 0x00
#define SET_OPEN_RELAY_STATE_STATE 0x00
#define OPEN_HV_STATUS 0x01
#define OPEN_GND_STATUS 0x01
